name: Smoke Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        
    - name: Install root dependencies
      run: npm ci
      
    - name: Install API dependencies
      if: exists('api/package.json')  # Only run if API exists
      run: npm ci
      working-directory: ./api  # Correct path
      
    - name: Load environment
      run: |
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" > api/.env
        echo "NODE_ENV=test" >> api/.env
        
    - name: Run tests
      run: npm test
      working-directory: ./api  # Run from API directory