name: Node.js CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        
    - name: Install dependencies (root)
      run: npm ci
      working-directory: ./  # Explicit root directory
      
    - name: Install dependencies (api)
      if: exists('api/package.json')  # Only run if api exists
      run: npm ci
      working-directory: ./api
      
    - name: Create .env
      run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" > ./api/.env
      
    - name: Run tests
      run: npm test